version: '3.8'
services:
  database:
    container_name: strays.postgres
    image: postgres:latest
    env_file: .env
    restart: always
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=strays-database
    ports:
      - '5432:5432'